name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - dev  # Trigger this action on push to main branch. Adjust if needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17' # Adjust the Java version as per your project's needs.

      - name: Build with Maven
        run: mvn clean package # Assuming you're using Maven. Adjust if using Gradle.

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to VM
        env:
          DEPLOY_SERVER: 172.16.229.163
          DEPLOY_USER: root
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_SSH_PASSWORD }} # You'll set this secret up in the next step
        run: |
          sshpass -p "$DEPLOY_PASSWORD" scp -o StrictHostKeyChecking=no target/your-spring-boot-app.jar $DEPLOY_USER@$DEPLOY_SERVER:/root/